CREATE TABLE CATEGORIA 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, DESCRIPCION NVARCHAR2(60) NOT NULL 
, CONSTRAINT CATEGORIA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE USUARIO 
(
  ALIAS VARCHAR2(30) NOT NULL 
, NOMBRE NVARCHAR2(30) NOT NULL 
, APELLIDOS NVARCHAR2(30) NOT NULL 
, DIRECCION NVARCHAR2(40) NOT NULL 
, CEDULA INTEGER NOT NULL 
, CORREO VARCHAR2(40) NOT NULL 
, CALIFICACION SMALLINT DEFAULT 5 NOT NULL 
, PASSWORD VARCHAR2(15) NOT NULL
, CONSTRAINT USUARIO_PK PRIMARY KEY
  (
    ALIAS 
  )
  ENABLE 
);

CREATE TABLE SUBCATEGORIA 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, IDCATEGORIA NUMBER NOT NULL 
, DESCRIPCION NVARCHAR2(60) NOT NULL 
, CONSTRAINT SUBCATEGORIA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TELEFONOXUSUARIO 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL 
, ALIASUSUARIO VARCHAR2(30) NOT NULL 
, NUMERO VARCHAR2(15) NOT NULL 
, DESCRIPCION NVARCHAR2(20) NOT NULL 
, CONSTRAINT TELEFONOXUSUARIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TIPOXUSUARIO 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 MINVALUE 1 NOT NULL 
, ALIASUSUARIO VARCHAR2(30) NOT NULL 
, DESCRIPCION NVARCHAR2(20) NOT NULL 
, CONSTRAINT TIPOXUSUARIO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE ITEM 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, PRECIO NUMBER(15, 2) NOT NULL 
, DESCRIPCION NVARCHAR2(50) NOT NULL 
, IDSUBCATEGORIA NUMBER NOT NULL 
, FOTO BLOB 
, CONSTRAINT ITEM_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE SUBASTA 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, IDITEM NUMBER NOT NULL 
, ALIASVENDEDOR VARCHAR2(30) NOT NULL 
, MODOENTREGA NVARCHAR2(30) NOT NULL 
, PRECIOINICIAL NUMBER(15, 2) NOT NULL 
, PRECIOACTUAL NUMBER(15, 2)
, FECHAHORAFIN DATE NOT NULL 
, COMENTARIOVENDEDOR NVARCHAR2(50) 
, COMENTARIOCOMPRADOR NVARCHAR2(50) 
, ALIASCOMPRADOR VARCHAR2(30) 
, CALIFICACIONSUBASTA SMALLINT DEFAULT 0 
, ESTADOSUBASTA SMALLINT DEFAULT 1 NOT NULL 
, CONSTRAINT SUBASTA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE PUJA 
(
  ID NUMBER GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL 
, ALIASCOMPRADOR VARCHAR2(30) NOT NULL 
, IDSUBASTA NUMBER NOT NULL 
, MONTO NUMBER(15, 2) NOT NULL 
, FECHAHORA DATE NOT NULL 
, CONSTRAINT PUJA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ITEM
ADD CONSTRAINT ITEM_FK1 FOREIGN KEY
(
  IDSUBCATEGORIA 
)
REFERENCES SUBCATEGORIA
(
  ID 
)
ENABLE;

ALTER TABLE PUJA
ADD CONSTRAINT PUJA_FK_COMPRADOR FOREIGN KEY
(
  ALIASCOMPRADOR 
)
REFERENCES USUARIO
(
  ALIAS 
)
ENABLE;

ALTER TABLE PUJA
ADD CONSTRAINT PUJA_FK_SUBASTA FOREIGN KEY
(
  IDSUBASTA 
)
REFERENCES SUBASTA
(
  ID 
)
ENABLE;

ALTER TABLE SUBASTA
ADD CONSTRAINT SUBASTA_FK_COMPRADOR FOREIGN KEY
(
  ALIASCOMPRADOR 
)
REFERENCES USUARIO
(
  ALIAS 
)
ENABLE;

ALTER TABLE SUBASTA
ADD CONSTRAINT SUBASTA_FK_ITEM FOREIGN KEY
(
  IDITEM 
)
REFERENCES ITEM
(
  ID 
)
ENABLE;

ALTER TABLE SUBASTA
ADD CONSTRAINT SUBASTA_FK_VENDEDOR FOREIGN KEY
(
  ALIASVENDEDOR 
)
REFERENCES USUARIO
(
  ALIAS 
)
ENABLE;

ALTER TABLE SUBCATEGORIA
ADD CONSTRAINT SUBCATEGORIA_FK_CATEGORIA FOREIGN KEY
(
  IDCATEGORIA 
)
REFERENCES CATEGORIA
(
  ID 
)
ENABLE;

ALTER TABLE TELEFONOXUSUARIO
ADD CONSTRAINT TELEFONOXUSUARIO_FK1 FOREIGN KEY
(
  ALIASUSUARIO 
)
REFERENCES USUARIO
(
  ALIAS 
)
ENABLE;

ALTER TABLE TIPOXUSUARIO
ADD CONSTRAINT TIPOXUSUARIO_FK1 FOREIGN KEY
(
  ALIASUSUARIO 
)
REFERENCES USUARIO
(
  ALIAS 
)
ENABLE;