insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('rsetterthwait0', 'Randi', 'Setterthwait', '867 Marcy Junction', 3779413, 'rsetterthwait0@ihg.com', 3, 'nPWVaewV2yL0');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('owayland1', 'Othello', 'Wayland', '2531 Arizona Lane', 9730128, 'owayland1@etsy.com', 1, 'obr3BWHz');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('rdonnett2', 'Rosella', 'Donnett', '32293 Mallory Trail', 5415579, 'rdonnett2@bluehost.com', 4, '0wNu58QBeUk');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('ahubbins3', 'Arlyne', 'Hubbins', '2 Stephen Plaza', 3152972, 'ahubbins3@4shared.com', 1, 'zRdDDHSN');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('rnoulton4', 'Ramsay', 'Noulton', '1 Redwing Parkway', 3036825, 'rnoulton4@bandcamp.com', 1, 'rHfW2ARXbGz');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('cbrickham5', 'Cosimo', 'Brickham', '571 Rieder Park', 7858427, 'cbrickham5@ted.com', 3, 'yD2rhjgId');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('kmcgrath6', 'Katalin', 'Mc Grath', '37658 Basil Circle', 1633895, 'kmcgrath6@adobe.com', 5, 'WQCzAcAg9');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('ngully7', 'Nora', 'Gully', '040 Oakridge Lane', 824443, 'ngully7@pinterest.com', 4, 'cKtjQcDV');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('lspatari8', 'Lorri', 'Spatari', '65182 Sutherland Place', 8549909, 'lspatari8@vinaora.com', 5, 'D8XZXIJ9');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('vcoo9', 'Velvet', 'Coo', '8679 Kenwood Terrace', 9026717, 'vcoo9@fc2.com', 2, 'lnWDO9eAXP');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('ecinoa', 'Eleen', 'Cino', '704 Talisman Lane', 3061849, 'ecinoa@ucoz.com', 4, '41iVhjl');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('dduckwithb', 'Darla', 'Duckwith', '0 Sommers Alley', 9380407, 'dduckwithb@cbslocal.com', 3, 'DE1XCQaO');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('smantramc', 'Sheila-kathryn', 'Mantram', '24 Mendota Center', 2626940, 'smantramc@baidu.com', 1, '30OJEP');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('alangthorned', 'Adda', 'Langthorne', '78730 Wayridge Alley', 7643934, 'alangthorned@sina.com.cn', 5, 'LVFFT7WyI23j');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('rbrushneene', 'Revkah', 'Brushneen', '8112 Morningstar Trail', 7149766, 'rbrushneene@admin.ch', 4, 'CQrquI7');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('tdabbesf', 'Tracie', 'Dabbes', '271 Holy Cross Trail', 7500505, 'tdabbesf@freewebs.com', 3, 'P4qRqnwTN2Z');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('rarnholdtg', 'Reid', 'Arnholdt', '0 New Castle Place', 1360570, 'rarnholdtg@merriam-webster.com', 5, '6y3dTAvNSS5');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('csmarth', 'Candice', 'Smart', '207 Debra Center', 4991795, 'csmarth@ucsd.edu', 4, 'SiY1d2HHGAH');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('jsapwelli', 'Julie', 'Sapwell', '3783 Marcy Parkway', 1621095, 'jsapwelli@constantcontact.com', 2, 'cJTwCDML');
insert into public."USUARIO" ("ALIAS", "NOMBRE", "APELLIDOS", "DIRECCION", "CEDULA", "CORREO", "CALIFICACION", "PASSWORD") values ('dsavilj', 'Domingo', 'Savil', '72046 Kim Drive', 5380173, 'dsavilj@friendfeed.com', 3, 'N7nptfce');

insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('rsetterthwait0', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('owayland1', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('rdonnett2', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('ahubbins3', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('rnoulton4', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('cbrickham5', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('kmcgrath6', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('ngully7', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('lspatari8', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('vcoo9', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('ecinoa', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('dduckwithb', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('smantramc', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('alangthorned', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('rbrushneene', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('tdabbesf', 'administrador');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('rarnholdtg', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('csmarth', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('jsapwelli', 'participante');
insert into public."TIPOXUSUARIO" ("ALIASUSUARIO", "DESCRIPCION") values ('dsavilj', 'administrador');
