/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostgreSQL;

import Oracle.*;

/**
 *
 * @author Kevin MM
 */
public class PostgreSQLConsultarUsuarioParticipante extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuarioParticipante
     */
    public PostgreSQLConsultarUsuarioParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonConsultarPUListarHistorialPujas = new javax.swing.JButton();
        BotonConsultarPUListarHistorialSubastas = new javax.swing.JButton();
        BotonConsultaPUCancelar = new javax.swing.JButton();
        LabelConsultarPUsuario = new javax.swing.JLabel();
        BotonConsultarPULogOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonConsultarPUListarHistorialPujas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPUListarHistorialPujas.setText("Historial Pujas Ganadoras");
        BotonConsultarPUListarHistorialPujas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarPUListarHistorialPujasActionPerformed(evt);
            }
        });

        BotonConsultarPUListarHistorialSubastas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPUListarHistorialSubastas.setText("Historial Subastas");
        BotonConsultarPUListarHistorialSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarPUListarHistorialSubastasActionPerformed(evt);
            }
        });

        BotonConsultaPUCancelar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultaPUCancelar.setText("Cancelar");
        BotonConsultaPUCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaPUCancelarActionPerformed(evt);
            }
        });

        LabelConsultarPUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelConsultarPUsuario.setText("Consultar Usuario");

        BotonConsultarPULogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPULogOut.setText("Log Out");
        BotonConsultarPULogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarPULogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelConsultarPUsuario)
                        .addGap(145, 145, 145)
                        .addComponent(BotonConsultarPULogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonConsultarPUListarHistorialPujas)
                            .addComponent(BotonConsultarPUListarHistorialSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonConsultaPUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelConsultarPUsuario)
                    .addComponent(BotonConsultarPULogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(271, 271, 271)
                .addComponent(BotonConsultarPUListarHistorialPujas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonConsultarPUListarHistorialSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(BotonConsultaPUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultarPULogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarPULogOutActionPerformed
        OraclePantallaInicial frame = new OraclePantallaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultarPULogOutActionPerformed

    private void BotonConsultaPUCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaPUCancelarActionPerformed
        OraclePantallaParticipante frame = new OraclePantallaParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultaPUCancelarActionPerformed

    private void BotonConsultarPUListarHistorialSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarPUListarHistorialSubastasActionPerformed
        OracleConsultarSubastasPorParticipante frame = new OracleConsultarSubastasPorParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultarPUListarHistorialSubastasActionPerformed

    private void BotonConsultarPUListarHistorialPujasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarPUListarHistorialPujasActionPerformed
        OracleConsultarPujasPorParticipante frame = new OracleConsultarPujasPorParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonConsultarPUListarHistorialPujasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgreSQLConsultarUsuarioParticipante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultaPUCancelar;
    private javax.swing.JButton BotonConsultarPUListarHistorialPujas;
    private javax.swing.JButton BotonConsultarPUListarHistorialSubastas;
    private javax.swing.JButton BotonConsultarPULogOut;
    private javax.swing.JLabel LabelConsultarPUsuario;
    // End of variables declaration//GEN-END:variables
}
