DROP TABLE public."PUJA";
DROP TABLE public."SUBASTA";
DROP TABLE public."ITEM";
DROP TABLE public."TIPOXUSUARIO";
DROP TABLE public."TELEFONOXUSUARIO";
DROP TABLE public."SUBCATEGORIA";
DROP TABLE public."USUARIO";
DROP TABLE public."CATEGORIA";