/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Kevin MM
 */
public class ConsultarUsuarioParticipante extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarUsuarioParticipante
     */
    public ConsultarUsuarioParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EntryConsultarPUAlias = new javax.swing.JTextField();
        BotonConsultarPUListarHistorialPujas = new javax.swing.JButton();
        BotonConsultarPUListarHistorialSubastas = new javax.swing.JButton();
        BotonConsultaPUCancelar = new javax.swing.JButton();
        LabelConsultarPUsuario = new javax.swing.JLabel();
        BotonConsultarPULogOut = new javax.swing.JButton();
        LabelConsultarPUAlias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EntryConsultarPUAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        BotonConsultarPUListarHistorialPujas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPUListarHistorialPujas.setText("Historial Pujas Ganadoras");

        BotonConsultarPUListarHistorialSubastas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPUListarHistorialSubastas.setText("Historial Subastas");

        BotonConsultaPUCancelar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultaPUCancelar.setText("Cancelar");

        LabelConsultarPUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelConsultarPUsuario.setText("Consultar Usuario");

        BotonConsultarPULogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonConsultarPULogOut.setText("Log Out");
        BotonConsultarPULogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultarPULogOutActionPerformed(evt);
            }
        });

        LabelConsultarPUAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelConsultarPUAlias.setText("Alias:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(373, 373, 373)
                                .addComponent(LabelConsultarPUAlias)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 255, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelConsultarPUsuario)
                                .addGap(145, 145, 145)))
                        .addComponent(BotonConsultarPULogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BotonConsultarPUListarHistorialPujas)
                            .addComponent(EntryConsultarPUAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonConsultarPUListarHistorialSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonConsultaPUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelConsultarPUsuario)
                    .addComponent(BotonConsultarPULogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(LabelConsultarPUAlias)
                .addGap(37, 37, 37)
                .addComponent(EntryConsultarPUAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(BotonConsultarPUListarHistorialPujas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BotonConsultarPUListarHistorialSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(BotonConsultaPUCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultarPULogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultarPULogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonConsultarPULogOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarUsuarioParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarUsuarioParticipante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonConsultaPUCancelar;
    private javax.swing.JButton BotonConsultarPUListarHistorialPujas;
    private javax.swing.JButton BotonConsultarPUListarHistorialSubastas;
    private javax.swing.JButton BotonConsultarPULogOut;
    private javax.swing.JTextField EntryConsultarPUAlias;
    private javax.swing.JLabel LabelConsultarPUAlias;
    private javax.swing.JLabel LabelConsultarPUsuario;
    // End of variables declaration//GEN-END:variables
}
