/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Kevin MM
 */
public class SubastarItem extends javax.swing.JFrame {

    /**
     * Creates new form SubastarItem
     */
    public SubastarItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelSubastar = new javax.swing.JLabel();
        BotonSubastarLogOut = new javax.swing.JButton();
        LabelSubastarPrecio = new javax.swing.JLabel();
        LabelSubastarDescripcion = new javax.swing.JLabel();
        LabelSubastarModoEntrega = new javax.swing.JLabel();
        LabelSubastarFechaLimite = new javax.swing.JLabel();
        LabelSubastarHoraLimite = new javax.swing.JLabel();
        EntrySubastaPrecio = new javax.swing.JTextField();
        EntrySubastaDescripcion = new javax.swing.JTextField();
        EntrySubastaModoDeEntrega = new javax.swing.JTextField();
        EntrySubastaFechaLimite = new javax.swing.JTextField();
        EntrySubastaHoraLimite = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        ComboBoxSubastarSubcategoria = new javax.swing.JComboBox<>();
        ComboBoxSubastarCategoria = new javax.swing.JComboBox<>();
        LabelSubastarCategoria = new javax.swing.JLabel();
        LabelSubastarSubcategoria = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelSubastar.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelSubastar.setText("Subastar Item");

        BotonSubastarLogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonSubastarLogOut.setText("Log Out");

        LabelSubastarPrecio.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarPrecio.setText("Precio:");

        LabelSubastarDescripcion.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarDescripcion.setText("Descripcion:");

        LabelSubastarModoEntrega.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarModoEntrega.setText("Modo de Entrega:");

        LabelSubastarFechaLimite.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarFechaLimite.setText("Fecha Límite:");

        LabelSubastarHoraLimite.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarHoraLimite.setText("Hora Límite:");

        EntrySubastaPrecio.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntrySubastaDescripcion.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntrySubastaModoDeEntrega.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntrySubastaFechaLimite.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        EntrySubastaFechaLimite.setToolTipText("Formato: YYYY/MM/DD");

        EntrySubastaHoraLimite.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        EntrySubastaHoraLimite.setToolTipText("HH24:MI:SS");

        jButton2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton2.setText("Agregar Imagen");

        ComboBoxSubastarSubcategoria.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        ComboBoxSubastarSubcategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subcategoria" }));

        ComboBoxSubastarCategoria.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        ComboBoxSubastarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria" }));

        LabelSubastarCategoria.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarCategoria.setText("Categoría:");

        LabelSubastarSubcategoria.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelSubastarSubcategoria.setText("Subcategoría");

        jButton1.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jButton1.setText("Subastar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/default.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addComponent(LabelSubastar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSubastarLogOut)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelSubastarDescripcion)
                            .addComponent(LabelSubastarFechaLimite)
                            .addComponent(LabelSubastarHoraLimite)
                            .addComponent(LabelSubastarPrecio)
                            .addComponent(LabelSubastarCategoria)
                            .addComponent(LabelSubastarSubcategoria)
                            .addComponent(LabelSubastarModoEntrega))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EntrySubastaModoDeEntrega)
                            .addComponent(ComboBoxSubastarSubcategoria, 0, 294, Short.MAX_VALUE)
                            .addComponent(ComboBoxSubastarCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EntrySubastaHoraLimite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrySubastaFechaLimite, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrySubastaDescripcion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrySubastaPrecio, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSubastar)
                    .addComponent(BotonSubastarLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelSubastarPrecio)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelSubastarDescripcion)
                            .addComponent(EntrySubastaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EntrySubastaModoDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelSubastarModoEntrega)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EntrySubastaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EntrySubastaFechaLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LabelSubastarFechaLimite)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelSubastarHoraLimite)
                    .addComponent(EntrySubastaHoraLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSubastarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSubastarCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxSubastarSubcategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSubastarSubcategoria))
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubastarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubastarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubastarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubastarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubastarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSubastarLogOut;
    private javax.swing.JComboBox<String> ComboBoxSubastarCategoria;
    private javax.swing.JComboBox<String> ComboBoxSubastarSubcategoria;
    private javax.swing.JTextField EntrySubastaDescripcion;
    private javax.swing.JTextField EntrySubastaFechaLimite;
    private javax.swing.JTextField EntrySubastaHoraLimite;
    private javax.swing.JTextField EntrySubastaModoDeEntrega;
    private javax.swing.JTextField EntrySubastaPrecio;
    private javax.swing.JLabel LabelSubastar;
    private javax.swing.JLabel LabelSubastarCategoria;
    private javax.swing.JLabel LabelSubastarDescripcion;
    private javax.swing.JLabel LabelSubastarFechaLimite;
    private javax.swing.JLabel LabelSubastarHoraLimite;
    private javax.swing.JLabel LabelSubastarModoEntrega;
    private javax.swing.JLabel LabelSubastarPrecio;
    private javax.swing.JLabel LabelSubastarSubcategoria;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
