/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin MM
 */
public class Pujar extends javax.swing.JFrame {

    public static int idSubasta;
    
    public Pujar() {
        initComponents();
    }
    
    public Pujar(int idSubasta_, String precioActual) {
        initComponents();
        
        idSubasta = idSubasta_;
        LabelMontoACambiar.setText(precioActual);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelPujar = new javax.swing.JLabel();
        BotonPujarLogOut = new javax.swing.JButton();
        LabelPujarMontoActual = new javax.swing.JLabel();
        LabelPujarPuja = new javax.swing.JLabel();
        LabelMontoACambiar = new javax.swing.JLabel();
        SpinnerPujarPuja = new javax.swing.JSpinner();
        BotonPujarPujar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelPujar.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelPujar.setText("Pujar");

        BotonPujarLogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonPujarLogOut.setText("Log Out");
        BotonPujarLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPujarLogOutActionPerformed(evt);
            }
        });

        LabelPujarMontoActual.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelPujarMontoActual.setText("Monto Actual:");

        LabelPujarPuja.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelPujarPuja.setText("Puja:");

        LabelMontoACambiar.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        LabelMontoACambiar.setText("$12345678");

        SpinnerPujarPuja.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        SpinnerPujarPuja.setModel(new javax.swing.SpinnerNumberModel(12345678, 12345678, null, 500));

        BotonPujarPujar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonPujarPujar.setText("Pujar");
        BotonPujarPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPujarPujarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelPujar)
                                .addGap(261, 261, 261)
                                .addComponent(BotonPujarLogOut)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BotonPujarPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPujarMontoActual)
                            .addComponent(LabelPujarPuja))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelMontoACambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SpinnerPujarPuja)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotonPujarLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LabelPujar)))
                .addGap(325, 325, 325)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPujarMontoActual)
                    .addComponent(LabelMontoACambiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinnerPujarPuja, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPujarPuja))
                .addGap(48, 48, 48)
                .addComponent(BotonPujarPujar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPujarLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPujarLogOutActionPerformed
        PantallaInicial frame = new PantallaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPujarLogOutActionPerformed

    private void BotonPujarPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPujarPujarActionPerformed
        ArrayList<String> rowsList = new ArrayList<>(); // List to store the rows from the query.
        
        String ALIASCOMPRADORv = PantallaInicial.aliasUsuario;
        String INCREMENTOMINIMOv = PantallaInicial.incrementominimo;
        String PORCENTAJEMEJORAv = PantallaInicial.porcentajemejora;
        String IDSUBASTAv = Integer.toString(idSubasta);
        String MONTOv = SpinnerPujarPuja.getValue().toString();
        
        Conexion con_ = new Conexion();
        Connection con = con_.CrearConexion();

        // Obtener índice subcategoría.
        
        String query = "PUJAR(INCREMENTOMINIMO=>" + INCREMENTOMINIMOv + ",PORCENTAJEMEJORA=>" + PORCENTAJEMEJORAv + 
            ",ALIASCOMPRADORv=>'" + ALIASCOMPRADORv + "',IDSUBASTAv=>" + IDSUBASTAv + ",MONTOv=>" + MONTOv + ")";
 
        rowsList = con_.EjecutarSP(query, con);
        
        // Close connection.
        try {
            con_.CerrarConexion(con);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Puja realizada con éxito");
        PantallaParticipante frame = new PantallaParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonPujarPujarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pujar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pujar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonPujarLogOut;
    private javax.swing.JButton BotonPujarPujar;
    private javax.swing.JLabel LabelMontoACambiar;
    private javax.swing.JLabel LabelPujar;
    private javax.swing.JLabel LabelPujarMontoActual;
    private javax.swing.JLabel LabelPujarPuja;
    private javax.swing.JSpinner SpinnerPujarPuja;
    // End of variables declaration//GEN-END:variables
}
