EXEC SP_CREAR_USUARIO(ALIASv=>'admin1',NOMBREv=>'admin1_nombre',APELLIDOSv=>'admin1_apellidos',DIRECCIONv=>'admin1_direccion',CEDULAv=>111222,CORREOv=>'admin1_correo',CALIFICACIONv=>5,PASSWORDv=>'admin1pw',NUMEROv=>111,TIPOUSUARIOv=>'ADMINISTRADOR');

SELECT * FROM C##_USUARIO_ADMIN.USUARIO;
SELECT * FROM C##_USUARIO_ADMIN.SUBASTA;
SELECT * FROM C##_USUARIO_ADMIN.PUJA;