/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostgreSQL;

import Oracle.*;

/**
 *
 * @author Kevin MM
 */
public class PostgreSQLPantallaParticipante extends javax.swing.JFrame {

    /**
     * Creates new form PantallaParticipante
     */
    public PostgreSQLPantallaParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelParticipante = new javax.swing.JLabel();
        BotonParticipanteLogOut = new javax.swing.JButton();
        BotonParticipanteSubastarItem = new javax.swing.JButton();
        BotonParticipanteListarSubastas = new javax.swing.JButton();
        BotonParticipanteConsultarUsuario = new javax.swing.JButton();
        BotonParticipanteCSubastasGanadasUsuario = new javax.swing.JButton();
        BotonParticipanteSubastasRealizadasUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PostgreSQL");

        LabelParticipante.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelParticipante.setText("Participante");

        BotonParticipanteLogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteLogOut.setText("Log Out");
        BotonParticipanteLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteLogOutActionPerformed(evt);
            }
        });

        BotonParticipanteSubastarItem.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteSubastarItem.setText("Subastar Item");
        BotonParticipanteSubastarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteSubastarItemActionPerformed(evt);
            }
        });

        BotonParticipanteListarSubastas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteListarSubastas.setText("Listar Subastas");
        BotonParticipanteListarSubastas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteListarSubastasActionPerformed(evt);
            }
        });

        BotonParticipanteConsultarUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteConsultarUsuario.setText("Subastas Ganadas");
        BotonParticipanteConsultarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteConsultarUsuarioActionPerformed(evt);
            }
        });

        BotonParticipanteCSubastasGanadasUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteCSubastasGanadasUsuario.setText("Subastas Realizadas");
        BotonParticipanteCSubastasGanadasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteCSubastasGanadasUsuarioActionPerformed(evt);
            }
        });

        BotonParticipanteSubastasRealizadasUsuario.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonParticipanteSubastasRealizadasUsuario.setText("Subastas Ganadoras");
        BotonParticipanteSubastasRealizadasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParticipanteSubastasRealizadasUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(319, Short.MAX_VALUE)
                        .addComponent(LabelParticipante)
                        .addGap(238, 238, 238)
                        .addComponent(BotonParticipanteLogOut))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(BotonParticipanteCSubastasGanadasUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonParticipanteSubastasRealizadasUsuario))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(BotonParticipanteListarSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonParticipanteSubastarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BotonParticipanteConsultarUsuario)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelParticipante)
                    .addComponent(BotonParticipanteLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(197, 197, 197)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonParticipanteSubastarItem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonParticipanteListarSubastas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonParticipanteConsultarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonParticipanteSubastasRealizadasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonParticipanteCSubastasGanadasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(264, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonParticipanteListarSubastasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteListarSubastasActionPerformed
        PostgreSQLConsultarSubastasParticipante frame = new PostgreSQLConsultarSubastasParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteListarSubastasActionPerformed

    private void BotonParticipanteSubastarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteSubastarItemActionPerformed
        PostgreSQLSubastarItem frame = new PostgreSQLSubastarItem();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteSubastarItemActionPerformed

    private void BotonParticipanteConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteConsultarUsuarioActionPerformed
        PostgreSQLConsultarUsuarioParticipante frame = new PostgreSQLConsultarUsuarioParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteConsultarUsuarioActionPerformed

    private void BotonParticipanteLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteLogOutActionPerformed
        PostgreSQLPantallaInicial frame = new PostgreSQLPantallaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteLogOutActionPerformed

    private void BotonParticipanteCSubastasGanadasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteCSubastasGanadasUsuarioActionPerformed
        PostgreSQLSubastasRealizadas frame = new PostgreSQLSubastasRealizadas();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteCSubastasGanadasUsuarioActionPerformed

    private void BotonParticipanteSubastasRealizadasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParticipanteSubastasRealizadasUsuarioActionPerformed
        PostgreSQLSubastasGanadoras frame = new PostgreSQLSubastasGanadoras();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonParticipanteSubastasRealizadasUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLPantallaParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLPantallaParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLPantallaParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLPantallaParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgreSQLPantallaParticipante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonParticipanteCSubastasGanadasUsuario;
    private javax.swing.JButton BotonParticipanteConsultarUsuario;
    private javax.swing.JButton BotonParticipanteListarSubastas;
    private javax.swing.JButton BotonParticipanteLogOut;
    private javax.swing.JButton BotonParticipanteSubastarItem;
    private javax.swing.JButton BotonParticipanteSubastasRealizadasUsuario;
    private javax.swing.JLabel LabelParticipante;
    // End of variables declaration//GEN-END:variables
}
