/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PostgreSQL;

import Oracle.*;
import Connections.OracleConnection;
import Connections.PostgreSQLConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin MM
 */
public class PostgreSQLConsultarSubastasPorParticipante extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarSubastasPorParticipante
     */
    public PostgreSQLConsultarSubastasPorParticipante() {
        initComponents();
        
        ArrayList<String> rowsList = new ArrayList<>(); // List to store the rows from the query.
        
        PostgreSQLConnection con_ = new PostgreSQLConnection();
        String columnName = "ft_select_users"; // Name of the returned column.

        rowsList = con_.FunctionReturningString("SELECT public.FT_SELECT_USERS()", columnName);
        
        // Adds to the combobox all the users.
        for (String user: rowsList) {
            ComboBoxModificarAlias.addItem(user);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonListarSubastasPPVolver = new javax.swing.JButton();
        LabelSubastasPP = new javax.swing.JLabel();
        BotonListarSubastasPPLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListListarSubastasPP = new javax.swing.JList<>();
        ComboBoxModificarAlias = new javax.swing.JComboBox<>();
        LabelModificarAlias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PostgreSQL");

        BotonListarSubastasPPVolver.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonListarSubastasPPVolver.setText("Volver");
        BotonListarSubastasPPVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarSubastasPPVolverActionPerformed(evt);
            }
        });

        LabelSubastasPP.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelSubastasPP.setText("Subastas");

        BotonListarSubastasPPLogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonListarSubastasPPLogOut.setText("Log Out");
        BotonListarSubastasPPLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonListarSubastasPPLogOutActionPerformed(evt);
            }
        });

        ListListarSubastasPP.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        jScrollPane1.setViewportView(ListListarSubastasPP);

        ComboBoxModificarAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        ComboBoxModificarAlias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario" }));
        ComboBoxModificarAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxModificarAliasActionPerformed(evt);
            }
        });

        LabelModificarAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarAlias.setText("Alias:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 120, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(LabelModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(ComboBoxModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonListarSubastasPPVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelSubastasPP)
                .addGap(212, 212, 212)
                .addComponent(BotonListarSubastasPPLogOut)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarSubastasPPLogOut)
                    .addComponent(LabelSubastasPP))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonListarSubastasPPVolver)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(LabelModificarAlias)
                        .addComponent(ComboBoxModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonListarSubastasPPVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarSubastasPPVolverActionPerformed
        PostgreSQLConsultarUsuarioParticipante frame = new PostgreSQLConsultarUsuarioParticipante();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonListarSubastasPPVolverActionPerformed

    private void BotonListarSubastasPPLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonListarSubastasPPLogOutActionPerformed
        PostgreSQLPantallaInicial frame = new PostgreSQLPantallaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonListarSubastasPPLogOutActionPerformed

    private void ComboBoxModificarAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxModificarAliasActionPerformed
        DefaultListModel model = new DefaultListModel();

        // Agrega al combobox todas las categorías
        ArrayList<String> rowsList = new ArrayList<>(); // List to store the rows from the query.

        String aliasSeleccionado = ComboBoxModificarAlias.getSelectedItem().toString();

        PostgreSQLConnection con_ = new PostgreSQLConnection();
        
        String columnName = "ft_listar_subastas_usuario"; // Name of the returned column.
        rowsList = con_.FunctionReturningString("SELECT FT_LISTAR_SUBASTAS_USUARIO (ALIASVENDEDORv:='" + aliasSeleccionado + "'::TEXT)", columnName);
        
        ListListarSubastasPP.removeAll();

        for (String subasta: rowsList) {
            model.addElement(subasta);
        }

        ListListarSubastasPP.setModel(model);
    }//GEN-LAST:event_ComboBoxModificarAliasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarSubastasPorParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarSubastasPorParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarSubastasPorParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PostgreSQLConsultarSubastasPorParticipante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PostgreSQLConsultarSubastasPorParticipante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonListarSubastasPPLogOut;
    private javax.swing.JButton BotonListarSubastasPPVolver;
    private javax.swing.JComboBox<String> ComboBoxModificarAlias;
    private javax.swing.JLabel LabelModificarAlias;
    private javax.swing.JLabel LabelSubastasPP;
    private javax.swing.JList<String> ListListarSubastasPP;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
