/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.Conexion;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author Kevin MM
 */
public class ModificarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarUsuario
     */
    public ModificarUsuario() {
        initComponents();
        EntryModificarPassword.setEchoChar('•');
        
        // Agrega al combobox todos los alias de los usuarios.
        ArrayList<String> rowsList = new ArrayList<>(); // List to store the rows from the query.
        
        Conexion con_ = new Conexion();
        Connection con = con_.CrearConexion();
        rowsList = con_.EjecutarSP("SP_SELECT_USERS", con);
        
        for (String user: rowsList) {
            ComboBoxModificarAlias.addItem(user);
            System.out.println(user);
        }
        
        // Close connection.
        try {
            con_.CerrarConexion(con);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelModificar = new javax.swing.JLabel();
        EntryModificarNombre = new javax.swing.JTextField();
        EntryModificarApellidos = new javax.swing.JTextField();
        EntryModificarDireccion = new javax.swing.JTextField();
        EntryModificarCedula = new javax.swing.JTextField();
        EntryModificarTelefonoPrincipal = new javax.swing.JTextField();
        EntryModificarCorreo = new javax.swing.JTextField();
        EntryModificarPassword = new javax.swing.JPasswordField();
        LabelModificarAlias = new javax.swing.JLabel();
        LabelModificarNombre = new javax.swing.JLabel();
        LabelModificarApellidos = new javax.swing.JLabel();
        LabelModificarDireccion = new javax.swing.JLabel();
        LabelModificarCedula = new javax.swing.JLabel();
        LabelModificarTelefono = new javax.swing.JLabel();
        LabelModificarCorreo = new javax.swing.JLabel();
        LabelModificarPassword = new javax.swing.JLabel();
        BotonActualizar = new javax.swing.JButton();
        BotonCancelarModificar = new javax.swing.JButton();
        BotonModificarLogOut = new javax.swing.JButton();
        ComboBoxModificarAlias = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelModificar.setFont(new java.awt.Font("Tw Cen MT", 0, 36)); // NOI18N
        LabelModificar.setText("Modificar Usuario");

        EntryModificarNombre.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarApellidos.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarDireccion.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarCedula.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarTelefonoPrincipal.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarCorreo.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        EntryModificarPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N

        LabelModificarAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarAlias.setText("Alias:");

        LabelModificarNombre.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarNombre.setText("Nombre:");

        LabelModificarApellidos.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarApellidos.setText("Apellidos:");

        LabelModificarDireccion.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarDireccion.setText("Direccion:");

        LabelModificarCedula.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarCedula.setText("Cedula:");

        LabelModificarTelefono.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarTelefono.setText("Telefono Principal:");

        LabelModificarCorreo.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarCorreo.setText("Correo:");

        LabelModificarPassword.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        LabelModificarPassword.setText("Password:");

        BotonActualizar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        BotonCancelarModificar.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonCancelarModificar.setText("Cancelar");
        BotonCancelarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCancelarModificarActionPerformed(evt);
            }
        });

        BotonModificarLogOut.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        BotonModificarLogOut.setText("Log Out");
        BotonModificarLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarLogOutActionPerformed(evt);
            }
        });

        ComboBoxModificarAlias.setFont(new java.awt.Font("Tw Cen MT", 0, 20)); // NOI18N
        ComboBoxModificarAlias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuario" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(LabelModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonModificarLogOut)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelModificarCedula)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelModificarTelefono)
                            .addComponent(LabelModificarDireccion)
                            .addComponent(LabelModificarApellidos)
                            .addComponent(LabelModificarNombre)
                            .addComponent(LabelModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelModificarCorreo)
                            .addComponent(LabelModificarPassword))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(EntryModificarNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addComponent(EntryModificarApellidos)
                                .addComponent(EntryModificarDireccion)
                                .addComponent(EntryModificarCedula)
                                .addComponent(EntryModificarTelefonoPrincipal)
                                .addComponent(EntryModificarCorreo)
                                .addComponent(EntryModificarPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonCancelarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ComboBoxModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(312, 312, 312))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelModificar)
                    .addComponent(BotonModificarLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelModificarAlias)
                    .addComponent(ComboBoxModificarAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarDireccion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarTelefonoPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarTelefono))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntryModificarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelModificarPassword))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonCancelarModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        ArrayList<String> rowsList = new ArrayList<>(); // List to store the rows from the query.
        
        String ALIASv = ComboBoxModificarAlias.getSelectedItem().toString();
        String NOMBREv = EntryModificarNombre.getText();
        String APELLIDOSv = EntryModificarApellidos.getText();
        String DIRECCIONv = EntryModificarDireccion.getText();
        String CEDULAv = EntryModificarCedula.getText();
        String NUMEROv = EntryModificarTelefonoPrincipal.getText();
        String CORREOv = EntryModificarCorreo.getText();
        String PASSWORDv = String.valueOf(EntryModificarPassword.getPassword());
        
        Conexion con_ = new Conexion();
        Connection con = con_.CrearConexion();
        String query = "SP_MODIFICAR_USUARIO(ALIASv=>'" + ALIASv + "'";
        
        if (!NOMBREv.isEmpty()) query += ",NOMBREv=>'"+ NOMBREv +"'";
        if (!APELLIDOSv.isEmpty()) query += ",APELLIDOSv=>'"+ APELLIDOSv +"'";
        if (!DIRECCIONv.isEmpty()) query += ",DIRECCIONv=>'"+ DIRECCIONv +"'";
        if (!CEDULAv.isEmpty()) query += ",CEDULAv=>'"+ CEDULAv +"'";
        if (!NUMEROv.isEmpty()) query += ",NUMEROv=>'"+ NUMEROv +"'";
        if (!CORREOv.isEmpty()) query += ",CORREOv=>'"+ CORREOv +"'";
        if (!PASSWORDv.isEmpty()) query += ",PASSWORDv=>'"+ PASSWORDv +"'";
        
        query += ")";
        rowsList = con_.EjecutarSP(query, con);
        
        String[] parts = rowsList.get(0).split(",");
        String success = parts[0];
        String usrType = parts[1];
        
        if (success.equals("1") && usrType.equals("ADMINISTRADOR")) {
            showMessageDialog(null, "Administrador actualizado.");
        } else if (success.equals("1") && usrType.equals("PARTICIPANTE")) {
            showMessageDialog(null, "Participante actualizado.");
        } else if (success.equals("0")) {
            showMessageDialog(null, "Alias no encontrado");
        }
        
        // Close connection.
        try {
            con_.CerrarConexion(con);
        } catch (SQLException ex) {
            Logger.getLogger(PantallaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PantallaAdmin frame = new PantallaAdmin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonModificarLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarLogOutActionPerformed
        PantallaInicial frame = new PantallaInicial();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonModificarLogOutActionPerformed

    private void BotonCancelarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCancelarModificarActionPerformed
        PantallaAdmin frame = new PantallaAdmin();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BotonCancelarModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonCancelarModificar;
    private javax.swing.JButton BotonModificarLogOut;
    private javax.swing.JComboBox<String> ComboBoxModificarAlias;
    private javax.swing.JTextField EntryModificarApellidos;
    private javax.swing.JTextField EntryModificarCedula;
    private javax.swing.JTextField EntryModificarCorreo;
    private javax.swing.JTextField EntryModificarDireccion;
    private javax.swing.JTextField EntryModificarNombre;
    private javax.swing.JPasswordField EntryModificarPassword;
    private javax.swing.JTextField EntryModificarTelefonoPrincipal;
    private javax.swing.JLabel LabelModificar;
    private javax.swing.JLabel LabelModificarAlias;
    private javax.swing.JLabel LabelModificarApellidos;
    private javax.swing.JLabel LabelModificarCedula;
    private javax.swing.JLabel LabelModificarCorreo;
    private javax.swing.JLabel LabelModificarDireccion;
    private javax.swing.JLabel LabelModificarNombre;
    private javax.swing.JLabel LabelModificarPassword;
    private javax.swing.JLabel LabelModificarTelefono;
    // End of variables declaration//GEN-END:variables
}
